export const ROLES = {
  CEO_JILA_PANCHAYAT: 'CEO Jila Panchayat',
  JILA_PANCHAYAT: 'Jila Panchayat',
  JANPAD: 'Janpad',
  GRAM_PANCHAYAT: 'Gram Panchayat',
  ENGINEER: 'Engineer',
  SUB_ENGINEER: 'Sub-Engineer',
  ACCOUNTANT: 'Accountant'
};

export const ROLE_ACCESS = {
  [ROLES.CEO_JILA_PANCHAYAT]: 'FULL',
  [ROLES.JILA_PANCHAYAT]: 'FULL',
  [ROLES.JANPAD]: 'FULL',
  [ROLES.GRAM_PANCHAYAT]: 'FULL',
  [ROLES.ENGINEER]: 'LIMITED',
  [ROLES.SUB_ENGINEER]: 'LIMITED',
  [ROLES.ACCOUNTANT]: 'FINANCE'
};